name: CI/CD for MediPass Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with: 
        path: MediPass-Backend

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: cd MediPass-Backend && mvn clean package -DskipTests

    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: medipass-jar
        path: MediPass-Backend/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download JAR Artifact
      uses: actions/download-artifact@v4
      with:
        name: medipass-jar
        path: target/

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "target/*.jar"
        target: "~/medipass-backend/medipass.jar"

    - name: Restart Backend Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          if ! java -version 2>&1 | grep '17'; then
            sudo apt update && sudo apt install -y openjdk-17-jdk
          fi
          pkill -f 'java -jar' || true
          nohup java -jar ~/medipass-backend/medipass.jar > ~/medipass-backend/app.log 2>&1 &
          echo "MediPass backend restarted successfully!"
