name: CI/CD for MediPass Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: medipass-jar
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download JAR Artifact
      uses: actions/download-artifact@v3
      with:
        name: medipass-jar
        path: target/

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host:13.48.190.240
        username:ubuntu
        key:MIIEpAIBAAKCAQEAs9Uz6wxz6beDnuN2niQI9PGX8V2+YHQckZHvkN/kJ28sdpn4
NFpt6J8TeiDfnxcV3vlk4hjW8AvZyGhkoufl4FqS7I7YtXPSNOv7o4tqOOLDmkI+
r2ngoeybruSt93ghfxItiFaheN+KFMCyvzr8hFjtZbAtN2dxSUV93a1XR1KmUUwp
4yhAggP07OdhPQnpWVJRh9Tzt48DZRdGUlqiIFhjdBEXfl5Fwtx0dwhEw+KPWo/K
EierrBeYCcARxYB/+1skWBX6BwaYORmreVzPVs259IlGXlWSQvAgXYfYYu0JMuJh
8Ltf/+l+f+jrSZj+XcL/4SSWN8O3i3+0al5C4wIDAQABAoIBAGMsWrtvXKUxbUa8
jnfby4y5h1+2oPy0S+UDpCgzMLGGn/CwLK9Ch4ZX4/fgFTK5Gnii9L2zkSVEg8//
sjAczysRCCGpDV3UB8LjuRySD/xbIh/6FHPMYfMqdxjWSBJHj8FyFuYvUFFGhfG3
61uGfifGmvUPWYBKbbFIv4b2x0EvKDKgw3x2r6FuxDPbq97+dUJINY7rGl4pMIdQ
1EiDY4jxg5g5ZfD2Qb1qZ3CiU7kv9wshlSjNPYLaLRSlNA6D7ZVSuuKddgqDs6Jc
QUa/4EIiQAfk+wXYpazQECVV0uH4GoPm3Kqqo5v9p2vr4l/txgOeVphg8IM9x20G
xtWzCkECgYEA47P1J9H4G8MtgQPjYovlbRlv3rKDCyCI7QMqYNWzvkb6EBIs8FFG
lfOcL4EHIcm6TuMc6N31gVmJiygFWudKrjgfwaFsn8FNZ7mpXuQtgZQk5Zd3sjBk
p3ezFNXOlDhe+lZq+8ixbSlJb9zeDdX0/mfpwuAP/iiK0KxCKulFZHECgYEAyi5T
WjORjPdmrtLYnpUwo2ZruLjXRovdJE3w82rGvFKYutAOS/atnk1jHM5iAOkaaOAa
8nhODn/GrHW1fwMZeMoD84MqF3psjGiaclQ1syYahwdIx1Bo/paOQP+K+BgslxWw
TR0X26TD0TNRQWkoDxSEJ1pcK5KDjcKQ9rWR9pMCgYEAq8PLcf9c1qxzvffN5j+7
kIH4tpgYbCNdxtR1eliaXzWxWsArMBlPUrxSnC8LzzwaE3oVC8CreqitLdDBwWHq
HuPtaKY5h4VMu6r9Dby4ax/yeVK6EyuYMhAEgfoK/BpN4y+fQlGRLdRQNlb5FpzI
U8TVPJDC36l7lY/r1ezj0LECgYBEPwLvzbxx4wkMNivcy+tRHL976RjxvUB2gsC0
yfQvmYnodVZ+GdRdPS4ZiSjXudeqUwuFkUp35nW/vTP4nak5dqeCyWGp7y847g5E
TVybDl+h+Ll+Xgwy88ss8ZWNTUuv7ChIv2tQPvvCYBorhD17aad6SSwXoSs67NRW
EtAkdQKBgQDUahxvMy964GlnqxlIVbyje8l0Uu4zjhnmhxlXyLOBBkzj0jdDSdCc
jOmYtoVGnoSrphL5YlsieAknIcE9MqHQ02PjNsLM2GhSztBj8ZHg+fZLpnvil4bn
CTVI4jyH6etpOayVkHpw4AMr8NBZLOMFgoW4VbR3RwJ6mv6I7YLz9g==
        source: "target/*.jar"
        target: "~/medipass-backend/medipass.jar"

    - name: Restart Backend Service
      uses: appleboy/ssh-action@master
      with:
        host: 13.48.190.240
        username: ubuntu
        key:MIIEpAIBAAKCAQEAs9Uz6wxz6beDnuN2niQI9PGX8V2+YHQckZHvkN/kJ28sdpn4
NFpt6J8TeiDfnxcV3vlk4hjW8AvZyGhkoufl4FqS7I7YtXPSNOv7o4tqOOLDmkI+
r2ngoeybruSt93ghfxItiFaheN+KFMCyvzr8hFjtZbAtN2dxSUV93a1XR1KmUUwp
4yhAggP07OdhPQnpWVJRh9Tzt48DZRdGUlqiIFhjdBEXfl5Fwtx0dwhEw+KPWo/K
EierrBeYCcARxYB/+1skWBX6BwaYORmreVzPVs259IlGXlWSQvAgXYfYYu0JMuJh
8Ltf/+l+f+jrSZj+XcL/4SSWN8O3i3+0al5C4wIDAQABAoIBAGMsWrtvXKUxbUa8
jnfby4y5h1+2oPy0S+UDpCgzMLGGn/CwLK9Ch4ZX4/fgFTK5Gnii9L2zkSVEg8//
sjAczysRCCGpDV3UB8LjuRySD/xbIh/6FHPMYfMqdxjWSBJHj8FyFuYvUFFGhfG3
61uGfifGmvUPWYBKbbFIv4b2x0EvKDKgw3x2r6FuxDPbq97+dUJINY7rGl4pMIdQ
1EiDY4jxg5g5ZfD2Qb1qZ3CiU7kv9wshlSjNPYLaLRSlNA6D7ZVSuuKddgqDs6Jc
QUa/4EIiQAfk+wXYpazQECVV0uH4GoPm3Kqqo5v9p2vr4l/txgOeVphg8IM9x20G
xtWzCkECgYEA47P1J9H4G8MtgQPjYovlbRlv3rKDCyCI7QMqYNWzvkb6EBIs8FFG
lfOcL4EHIcm6TuMc6N31gVmJiygFWudKrjgfwaFsn8FNZ7mpXuQtgZQk5Zd3sjBk
p3ezFNXOlDhe+lZq+8ixbSlJb9zeDdX0/mfpwuAP/iiK0KxCKulFZHECgYEAyi5T
WjORjPdmrtLYnpUwo2ZruLjXRovdJE3w82rGvFKYutAOS/atnk1jHM5iAOkaaOAa
8nhODn/GrHW1fwMZeMoD84MqF3psjGiaclQ1syYahwdIx1Bo/paOQP+K+BgslxWw
TR0X26TD0TNRQWkoDxSEJ1pcK5KDjcKQ9rWR9pMCgYEAq8PLcf9c1qxzvffN5j+7
kIH4tpgYbCNdxtR1eliaXzWxWsArMBlPUrxSnC8LzzwaE3oVC8CreqitLdDBwWHq
HuPtaKY5h4VMu6r9Dby4ax/yeVK6EyuYMhAEgfoK/BpN4y+fQlGRLdRQNlb5FpzI
U8TVPJDC36l7lY/r1ezj0LECgYBEPwLvzbxx4wkMNivcy+tRHL976RjxvUB2gsC0
yfQvmYnodVZ+GdRdPS4ZiSjXudeqUwuFkUp35nW/vTP4nak5dqeCyWGp7y847g5E
TVybDl+h+Ll+Xgwy88ss8ZWNTUuv7ChIv2tQPvvCYBorhD17aad6SSwXoSs67NRW
EtAkdQKBgQDUahxvMy964GlnqxlIVbyje8l0Uu4zjhnmhxlXyLOBBkzj0jdDSdCc
jOmYtoVGnoSrphL5YlsieAknIcE9MqHQ02PjNsLM2GhSztBj8ZHg+fZLpnvil4bn
CTVI4jyH6etpOayVkHpw4AMr8NBZLOMFgoW4VbR3RwJ6mv6I7YLz9g==
        script: |
          # Ensure Java 17 is installed
          if ! java -version 2>&1 | grep '17'; then
            sudo apt update && sudo apt install -y openjdk-17-jdk
          fi

          # Stop any running instance
          pkill -f 'java -jar' || true

          # Start as a background service
          nohup java -jar ~/medipass-backend/medipass.jar > ~/medipass-backend/app.log 2>&1 &

          echo "MediPass backend restarted successfully!"
